- name: Add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
  tags: install

- name: Add apt repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
  tags: install

- name: Update apt
  apt:
    update_cache: yes
  tags: install

- name: Install MongoDB package
  apt:
    name: mongodb-org
  tags: install

- name: Enable mongod
  systemd: name=mongod enabled=yes state=started
  tags: install
