plugin: gcp_compute
projects:
  - infra-219315
filters: null
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  internal_ip: networkInterfaces[0].networkIP
keyed_groups:
  - key: labels
    separator: ""
scopes:
  - https://www.googleapis.com/auth/gcp-compute
service_account_file: ~/.ansible/Infra-52b84a15aebf.json
auth_kind: serviceaccount
