---
- name: Instal MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
    - name: Add apt repo
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    - name: Update apt
      apt:
        update_cache: yes
    - name: Install MongoDB package
      apt:
        name: mongodb-org
    - name: Enable mongod
      systemd: name=mongod enabled=yes
